In [1]:
## Import necessary packages
import pandas as pd
import numpy as np
import camelot
import warnings
warnings.filterwarnings("ignore")

##  Missouri

### DWSRF Fiscal Year 2023 Project Priority Lists (Lead Service Line)

In [28]:
print("Parsing...")
# get the full table
mo_pdfs = camelot.read_pdf("../data/year1/pdf/MO/federal-fiscal-year-2023-drinking-water-state-revolving-fund-project-lists-amendment-2-approved_0-2.pdf", 
                           pages='13-20', flavor='stream', row_tol=10)
print(len(mo_pdfs))

Parsing...
8

In [12]:
mo_1 = mo_pdfs[0].df

# drop column name and total rows
mo_1 = mo_1.iloc[4:30,].reset_index(drop=True).copy()

# manually fix one row of merged columns
mo_1.iloc[16,0] = "D"
mo_1.iloc[16,1] = "Walker"

# set columns
mo_1.columns = ['Disadvantaged', 'Applicant', "Project #", 'Description/Needs Category', 'Service Area Population',
                'IUP Amount Requested', 'Loan Amount', 'Additional Subsidization Amount']

# remove line breaks
mo_1['IUP Amount Requested'] = mo_1['IUP Amount Requested'].str.replace("\n", "")
mo_1['Loan Amount'] = mo_1['Loan Amount'].str.replace("\n", "")
mo_1['Additional Subsidization Amount'] = mo_1['Additional Subsidization Amount'].str.replace("\n", "")

,Disadvantaged,Applicant,Project #,Description/Needs Category,Service Area Population,IUP Amount Requested,Loan Amount,Additional Subsidization Amount
0,D,St. Louis Water,DWLSL-101-23,LSLI,"304,709","$ 400,000",$ -,"$ 400,000"
1,,Platte County PWSD No. 8,DWLSL-102-23,LSLI,"1,176","$ 100,000","$ 59,000","$ 41,000"
2,D,Rosebud,DWLSL-103-23,"LSLI, LSLRP",627,"78,687$",$ -,"78,687$"
3,,Cole County PWSD No. 4,DWLSL-104-23,"LSLI, LSLRP, LSLR","3,000","$ 225,000","$ 132,750","$ 92,250"
4,D,Ellington,DWLSL-105-23,LSLI,790,"200,000$",$ -,"200,000$"
5,D,Freeburg,DWLSL-106-23,LSLI,437,"$ 110,000",$ -,"110,000$"
6,,Ashland,DWLSL-107-23,"LSLI, LSLRP","4,747","$ 200,000","$ 118,000","$ 82,000"
7,D,California,DWLSL-108-23,"LSLI, LSLRP, LSLR","4,411","225,000$",$ -,"225,000$"
8,,Park Hills,DWLSL-109-23,LSLI,"8,708","$ 200,000","$ 118,000","$ 82,000"
9,D,Bourbon,DWLSL-110-23,"LSLI, LSLRP","1,866","$ 150,000",$ -,"$ 150,000"
10,D,Mercer,DWLSL-111-23,LSLI,318,"12,000$",$ -,"12,000$"
11,,Kirksville,DWLSL-112-23,LSLI,"17,530","$ 50,000","$ 29,500","$ 20,500"
12,,Vernon CPWSD 1,DWLSL-113-23,"LSLI, LSLRP","8,925","$ 240,000","$ 141,600","$ 98,400"
13,D,Reynolds PWSD 1,DWLSL-114-23,LSLI,634,"$ 22,200",$ -,"$ 22,200"
14,,Boone PWSD 10,DWLSL-115-23,"LSLI, LSLRP","4,625","$ 202,000","$ 119,180","$ 82,820"
15,D,Braymer,DWLSL-116-23,"LSLI, LSLRP",660,"$ 135,000",$ -,"$ 135,000"
16,D,Walker,DWLSL-117-23,"LSLI, LSLRP",404,"$ 130,000",$ -,"$ 130,000"
17,D,Sullivan PWSD 1,DWLSL-118-23,LSLI,"3,183","$ 200,000",$ -,"$ 200,000"
18,D,Shelby PWSD 1,DWLSL-119-23,"LSLI, LSLRP","3,074","$ 202,000",$ -,"$ 202,000"
19,,Wellington,DWLSL-120-23,"LSLI, LSLRP",812,"$ 78,750","$ 46,463","$ 32,287"
20,D,Unionville,DWLSL-121-23,LSLI,"1,827","$ 200,000",$ -,"$ 200,000"
21,D,Clark County CPWSD 1,DWLSL-122-23,LSLI,"7,140","$ 500,000",$ -,"$ 500,000"
22,D,Atchison PWSD 1,DWLSL-123-23,"LSLI, LSLRP",703,"$ 85,287",$ -,"$ 85,287"
23,D,Henry County Water Company,DWLSL-124-23,"LSLI, LSLRP","8,792","$ 520,000",$ -,"$ 520,000"
24,,Ray County PWSD 2,DWLSL-125-23,LSLI,"9,750","$ 250,000","$ 147,500","$ 102,500"
25,D,Leadwood,DWLSL-126-23,"LSLI, LSLRP","1,192","$ 300,000",$ -,"$ 300,000"

In [15]:
mo_2 = mo_pdfs[1].df

# manually fix merged columns
mo_2.iloc[19,0] = "D"
mo_2.iloc[19,1] = "Williamsville"

mo_2.iloc[25,0] = "D"
mo_2.iloc[25,1] = "Wheatland"

# set columns
mo_2.columns = ['Disadvantaged', 'Applicant', "Project #", 'Description/Needs Category', 'Service Area Population',
                'IUP Amount Requested', 'Loan Amount', 'Additional Subsidization Amount']

# remove line breaks
mo_2['IUP Amount Requested'] = mo_2['IUP Amount Requested'].str.replace("\n", "")
mo_2['Loan Amount'] = mo_2['Loan Amount'].str.replace("\n", "")
mo_2['Additional Subsidization Amount'] = mo_2['Additional Subsidization Amount'].str.replace("\n", "")

,Disadvantaged,Applicant,Project #,Description/Needs Category,Service Area Population,IUP Amount Requested,Loan Amount,Additional Subsidization Amount
0,D,Viburnum,DWLSL-127-23,"LSLI, LSLRP",643,"300,000$",$ -,"$ 300,000"
1,D,Meta,DWLSL-128-23,"LSLRP, LSLR",108,"$ 25,000",$ -,"$ 25,000"
2,D,Ripley County PWSD No. 1,DWLSL-129-23,LSLI,"2,598","$ 300,000",$ -,"$ 300,000"
3,D,Ava,DWLSL-130-23,"LSLI, LSLRP, LSLR","2,903","225,000$",$ -,"225,000$"
4,,Centertown,DWLSL-131-23,"LSLI, LSLRP",309,"$ 150,000","$ 88,500","$ 61,500"
5,D,Schuyler CPWSD 1,DWLSL-132-23,LSLI,"3,176","200,000$",$ -,"$ 200,000"
6,D,Madison PWSD 1,DWLSL-133-23,LSLI,"2,610","$ 300,000",$ -,"300,000$"
7,,Jackson PWSD 2,DWLSL-134-23,LSLI,"16,500","$ 70,000","$ 41,300","$ 28,700"
8,,Centralia,DWLSL-135-23,LSLI,"4,651","500,000$","$ 397,500","$ 102,500"
9,,Marshfield,DWLSL-136-23,LSLI,"7,425","$ 350,000","$ 247,500","$ 102,500"
10,D,Appleton City,DWLSL-137-23,LSLI,"1,126","$ 80,000",$ -,"$ 80,000"
11,D,Keytesville,DWLSL-138-23,LSLI,441,"23,500$",$ -,"23,500$"
12,,Stone PWSD 1,DWLSL-139-23,"LSI, LSLRP","2,130","$ 30,640","$ 18,078","$ 12,562"
13,D,Laurie,DWLSL-140-23,LSLRP,916,"25,000$",$ -,"$ 25,000"
14,D,Mansfield,DWLSL-141-23,LSLI,"1,193","35,000$",$ -,"$ 35,000"
15,D,Pilot Knob,DWLSL-142-23,"LSLI, LSLRP",671,"$ 300,000",$ -,"$ 300,000"
16,D,Parma,DWLSL-143-23,"LSLI, LSLRP",555,"177,625$",$ -,"177,625$"
17,D,Naylor,DWLSL-144-23,LSLI,731,"$ 200,000",$ -,"200,000$"
18,D,Bollinger PWSD 1,DWLSL-145-23,"LSLI, LSLRP",225,"$ 300,000",$ -,"300,000$"
19,D,Williamsville,DWLSL-146-23,"LSLI, LSLRP",335,"$ 178,000",$ -,"$ 178,000"
20,D,Caledonia,DWLSL-147-23,"LSLI, LSLRP",133,"$ 80,000",$ -,"$ 80,000"
21,,Purdy,DWLSL-148-23,LSLI,"1,031","$ 250,000","$ 147,500","$ 102,500"
22,,Highlandville,DWLSL-149-23,LSLI,"1,529","$ 325,500","$ 223,000","$ 102,500"
23,D,Ripley County PWSD No. 2,DWLSL-150-23,"LSLI, LSLRP","4,352","$ 269,250",$ -,"$ 269,250"
24,,Kansas City,DWLSL-151-23,"LSLI, LSLRP","512,000","$ 3,570,000","$ 3,467,500","$ 102,500"
25,D,Wheatland,DWLSL-152-23,"LSLI, LSLRP",388,"$ 100,000",$ -,"$ 100,000"
26,D,Marble Hill,DWLSL-153-23,"LSLI, LSLRP","2,001","$ 142,200",$ -,"$ 142,200"
27,D,Advance,DWLSL-154-23,"LSLI, LSLRP","1,400","$ 200,250",$ -,"$ 200,250"
28,D,Pattonsburg,DWLSL-155-23,"LSLI, LSLRP",348,"$ 250,000",$ -,"$ 250,000"
29,D,Lamar,DWLSL-156-23,LSLI,"4,266","$ 105,315",$ -,"$ 105,315"
30,,Oak Grove,DWLSL-157-23,LSLI,"8,112","$ 100,000","$ 59,000","$ 41,000"
31,D,Cannon PWSD #1,DWLSL-158-23,LSLI,"6,482","$ 500,000",$ -,"$ 500,000"

In [17]:
mo_3 = mo_pdfs[2].df


# manually fix merged columns
mo_3.iloc[15,0] = "D"
mo_3.iloc[15,1] = "Wayne & Butler PWSSD 4"

mo_3.iloc[21,0] = "D"
mo_3.iloc[21,1] = "Weableau Public Water Supply"

# set columns
mo_3.columns = ['Disadvantaged', 'Applicant', "Project #", 'Description/Needs Category', 'Service Area Population',
                'IUP Amount Requested', 'Loan Amount', 'Additional Subsidization Amount']

# remove line breaks
mo_3['IUP Amount Requested'] = mo_3['IUP Amount Requested'].str.replace("\n", "")
mo_3['Loan Amount'] = mo_3['Loan Amount'].str.replace("\n", "")
mo_3['Additional Subsidization Amount'] = mo_3['Additional Subsidization Amount'].str.replace("\n", "")

,Disadvantaged,Applicant,Project #,Description/Needs Category,Service Area Population,IUP Amount Requested,Loan Amount,Additional Subsidization Amount
0,D,Sweet Springs,DWLSL-159-23,"LSLI, LSLRP","1,316","250,000$",$ -,"$ 250,000"
1,D,Osceola,DWLSL-160-23,LSLI,919,"$ 40,000",$ -,"$ 40,000"
2,D,"Barton, Dade, Cedar, Jasper CPWSD 1",DWLSL-161-23,"LSLI, LSLRP","9,375","178,308$",$ -,"178,308$"
3,,Cole PWSD No. 2,DWLSL-162-23,LSLI,"12,985","$ 1,200,000","$ 1,097,500","$ 102,500"
4,D,Pilot Knob Rural Water District,DWLSL-163-23,"LSLI, LSLRP","1,449","$ 300,000",$ -,"$ 300,000"
5,,Lee's Summit,DWLSL-164-23,LSLI,"9,110","252,255$","$ 149,755","102,500$"
6,,Fulton,DWLSL-165-23,"LSLI, LSLRP","12,721","$ 250,000","$ 147,500","$ 102,500"
7,D,Bowling Green,DWLSL-166-23,"LSLI, LSLRP","5,334","$ 80,000",$ -,"$ 80,000"
8,,Matthews,DWLSL-167-23,LSLI,635,"150,000$","$ 88,500","61,500$"
9,D,Laredo,DWLSL-168-23,LSLI,200,"$ 60,000",$ -,"$ 60,000"
10,D,Carrollton,DWLSL-169-23,"LSLRP, LSLR","3,514","208,594$",$ -,"$ 208,594"
11,D,Drexel,DWLSL-170-23,LSLI,965,"$ 250,000",$ -,"250,000$"
12,,Boonville,DWLSL-171-23,LSLI,"7,964","$ 78,100","$ 46,079","$ 32,021"
13,,Excelsior Springs,DWLSL-172-23,"LSLI, LSLRP","13,198","$ 132,500","$ 78,175","54,325$"
14,D,Vandalia,DWLSL-173-23,LSLI,"3,553","$ 250,000",$ -,"250,000$"
15,D,Wayne & Butler PWSSD 4,DWLSL-174-23,LSLI,"1,850","$ 250,000",$ -,"$ 250,000"
16,D,Arcadia,DWLSL-175-23,"LSLI, LSLRP",643,"275,000$",$ -,"275,000$"
17,D,Monett,DWLSL-176-23,LSLI,"9,576","$ 144,388",$ -,"$ 144,388"
18,D,Linn,DWLSL-177-23,LSLI,"1,507","$ 150,000",$ -,"$ 150,000"
19,D,Jasper,DWLSL-178-23,LSLI,985,"$ 30,000",$ -,"$ 30,000"
20,,Ash Grove,DWLSL-179-23,LSLI,"1,512","$ 250,000","$ 147,500","$ 102,500"
21,D,Weableau Public Water Supply\t,DWLSL-180-23,"LSLI, LSLRP",418,"$ 100,000",$ -,"$ 100,000"
22,,Holcomb,DWLSL-181-23,"LSLI, LSLRP",746,"$ 167,808","$ 99,007","$ 68,801"
23,,Buckner,DWLSL-182-23,LSLI,"3,448","$ 87,000","$ 51,330","$ 35,670"
24,D,Senath,DWLSL-183-23,LSLI,"1,721","$ 350,000",$ -,"$ 350,000"
25,D,Village of Big Lake,DWLSL-184-23,"LSLI, LSLRP, LSLR","2,000","$ 65,000",$ -,"$ 65,000"
26,D,Leeton,DWLSL-185-23,LSLI,612,"$ 166,400",$ -,"$ 166,400"
27,D,Daviess PWSD 2,DWLSL-186-23,LSLI,"2,578","$ 250,000",$ -,"$ 250,000"
28,,Puxico,DWLSL-187-23,"LSLI, LSLRP",873,"$ 166,900","$ 98,471","$ 68,429"
29,,MO American Platte County,DWLSL-188-23,LSLI,"18,213","$ 1,893,360","$ 1,790,860","$ 102,500"
30,,MO American Eureka,DWLSL-189-23,LSLI,"12,154","$ 901,110","$ 798,610","$ 102,500"

In [19]:
mo_4 = mo_pdfs[3].df

# set columns
mo_4.columns = ['Disadvantaged', 'Applicant', "Project #", 'Description/Needs Category', 'Service Area Population',
                'IUP Amount Requested', 'Loan Amount', 'Additional Subsidization Amount']

# remove line breaks
mo_4['IUP Amount Requested'] = mo_4['IUP Amount Requested'].str.replace("\n", "")
mo_4['Loan Amount'] = mo_4['Loan Amount'].str.replace("\n", "")
mo_4['Additional Subsidization Amount'] = mo_4['Additional Subsidization Amount'].str.replace("\n", "")

,Disadvantaged,Applicant,Project #,Description/Needs Category,Service Area Population,IUP Amount Requested,Loan Amount,Additional Subsidization Amount
0,,MO American Tri-State,DWLSL-190-23,LSLI,"9,265","$ 785,470","$ 682,970","102,500$"
1,,MO American Warrensburg,DWLSL-191-23,LSLI,"19,638","$ 695,380","$ 592,880","$ 102,500"
2,,MO American Lawson,DWLSL-192-23,LSLI,"2,526","$ 430,220","$ 327,720","$ 102,500"
3,,MO American Stonebridge Village,DWLSL-193-23,LSLI,"2,183","427,770$","$ 325,270","$ 102,500"
4,D,MO American Garden City,DWLSL-194-23,LSLI,"1,614","$ 376,810",$ -,"$ 376,810"
5,D,MO American Brunswick,DWLSL-195-23,LSLI,788,"242,550$",$ -,"$ 242,550"
6,D,MO American Emerald Pointe,DWLSL-196-23,LSLI,"1,298","$ 222,950",$ -,"222,950$"
7,,MO American Maplewood,DWLSL-197-23,LSLI,"1,010","$ 192,570","$ 113,616","$ 78,954"
8,,MO American Orrick,DWLSL-198-23,LSLI,738,"192,570$","$ 113,616","$ 78,954"
9,D,MO American Stewartsville,DWLSL-199-23,LSLI,750,"$ 178,850",$ -,"178,850$"
10,,MO American Smithton,DWLSL-200-23,LSLI,513,"$ 125,440","$ 74,010","$ 51,430"
11,,MO American Wardsville,DWLSL-201-23,LSLI,"1,616","102,410$","$ 60,422","$ 41,988"
12,D,MO American Ozark Mountain 2,DWLSL-202-23,LSLI,598,"$ 99,470",$ -,"$ 99,470"
13,,MO American Warren County,DWLSL-203-23,LSLI,"1,620","96,530$","$ 56,953","$ 39,577"
14,,MO American Purcell,DWLSL-204-23,LSLI,317,"93,590$","$ 55,218","$ 38,372"
15,D,MO American White Branch,DWLSL-205-23,LSLI,423,"$ 82,810",$ -,"$ 82,810"
16,,MO American Ozark Mountain 1,DWLSL-206-23,LSLI,415,"$ 69,090","$ 40,763","28,327$"
17,,MO American Riverside Estates,DWLSL-207-23,LSLI,823,"$ 68,600","$ 40,474","28,126$"
18,D,MO American Rogue Creek,DWLSL-208-23,LSLI,338,"$ 48,020",$ -,"48,020$"
19,D,MO American Ozark Mountain 3,DWLSL-209-23,LSLI,318,"$ 47,530",$ -,"$ 47,530"
20,,MO American Spring Valley Estates,DWLSL-210-23,LSLI,305,"$ 46,550","$ 27,465","$ 19,085"
21,,MO American Rankin Acres,DWLSL-211-23,LSLI,228,"$ 42,630","$ 25,152","$ 17,478"
22,,MO American Saddlebrook Village,DWLSL-212-23,LSLI,415,"$ 36,260","$ 21,393","$ 14,867"
23,,MO American Woodland Manor,DWLSL-213-23,LSLI,438,"$ 35,280","$ 20,815","$ 14,465"
24,,MO American Lake Taneycomo Acres,DWLSL-214-23,LSLI,275,"$ 34,300","$ 20,237","$ 14,063"
25,,MO American Pom-O-Sa Heights,DWLSL-215-23,LSLI,153,"$ 29,890","$ 17,635","$ 12,255"
26,,MO American Jefferson City Northern,DWLSL-216-23,LSLI,143,"$ 27,930","$ 16,479","$ 11,451"
27,D,MO American Monsees Lake Estates,DWLSL-217-23,LSLI,160,"$ 27,440",$ -,"$ 27,440"
28,,MO American Jaxson Estates,DWLSL-218-23,LSLI,543,"$ 26,583","$ 15,684","$ 10,899"
29,D,MO American Hickory Hills,DWLSL-219-23,LSLI,130,"$ 22,050",$ -,"$ 22,050"
30,,MO American Pevely Farms,DWLSL-220-23,LSLI,433,"$ 21,193","$ 12,504","$ 8,689"
31,,MO American Anna Meadows,DWLSL-221-23,LSLI,400,"$ 19,600","$ 11,564","$ 8,036"
32,,MO American Lake Carmel,DWLSL-222-23,LSLI,195,"$ 19,110","$ 11,275","$ 7,835"

In [22]:
mo_5 = mo_pdfs[4].df

# manually fix merged columns
mo_5.iloc[24,0] = "D"
mo_5.iloc[24,1] = "Windsor"

# set columns
mo_5.columns = ['Disadvantaged', 'Applicant', "Project #", 'Description/Needs Category', 'Service Area Population',
                'IUP Amount Requested', 'Loan Amount', 'Additional Subsidization Amount']

# remove line breaks
mo_5['IUP Amount Requested'] = mo_5['IUP Amount Requested'].str.replace("\n", "")
mo_5['Loan Amount'] = mo_5['Loan Amount'].str.replace("\n", "")
mo_5['Additional Subsidization Amount'] = mo_5['Additional Subsidization Amount'].str.replace("\n", "")

,Disadvantaged,Applicant,Project #,Description/Needs Category,Service Area Population,IUP Amount Requested,Loan Amount,Additional Subsidization Amount
0,,MO American Lakewood Manor,DWLSL-223-23,LSLI,98,"$ 15,190","$ 8,962","6,228$"
1,D,MO American Table Rock Estates,DWLSL-224-23,LSLI,93,"$ 12,250",$ -,"$ 12,250"
2,,MO American Golden Acres,DWLSL-225-23,LSLI,80,"11,270$","$ 6,649","4,621$"
3,,MO American Spokane Heights,DWLSL-226-23,LSLI,633,"$ 6,860","$ 4,047","2,813$"
4,,MO American Redfield,DWLSL-227-23,LSLI,93,"$ 6,860","$ 4,047","$ 2,813"
5,D,Fairfax,DWLSL-228-23,LSLI,695,"32,000$",$ -,"32,000$"
6,D,Steele,DWLSL-229-23,LSLI,"1,975","$ 250,000",$ -,"$ 250,000"
7,D,Clarkton,DWLSL-230-23,LSLI,"1,105","$ 220,000",$ -,"$ 220,000"
8,D,Bell City,DWLSL-231-23,LSLI,494,"228,000$",$ -,"228,000$"
9,D,Lincoln,DWLSL-232-23,LSLI,"1,360","$ 129,096",$ -,"$ 129,096"
10,,West Plains,DWLSL-233-23,LSLI,"12,184","$ 125,625","$ 74,119","$ 51,506"
11,D,Versailles,DWLSL-234-23,LSLI,"2,963","$ 192,000",$ -,"192,000$"
12,,Cape Girardeau,DWLSL-235-23,LSLI,"39,540","$ 500,000","$ 397,500","$ 102,500"
13,,Cass PWSD 2,DWLSL-236-23,LSLI,"5,500","$ 498,000","$ 395,500","102,500$"
14,,Oran,DWLSL-237-23,LSLI,"1,285","$ 300,000","$ 197,500","$ 102,500"
15,D,Madison,DWLSL-238-23,LSLI,515,"$ 154,250",$ -,"$ 154,250"
16,,Boone PWSD 4,DWLSL-239-23,LSLI,"7,290","78,894$","$ 46,547","$ 32,347"
17,D,McDonald PWSD 2,DWLSL-240-23,LSLI,"2,301","$ 250,000",$ -,"$ 250,000"
18,,Johnson PWSD 3,DWLSL-241-23,LSLI,"9,191","$ 243,007","$ 143,374","$ 99,633"
19,,Lincoln PWSD 2,DWLSL-242-23,LSLI,998,"$ 114,600","$ 67,614","$ 46,986"
20,D,La Plata,DWLSL-243-23,LSLI,"1,266","$ 240,000",$ -,"$ 240,000"
21,,Pike PWSD 1,DWLSL-244-23,"LSLI, LSLRP","6,655","$ 400,000","$ 297,500","$ 102,500"
22,D,Atlanta,DWLSL-245-23,LSLI,385,"$ 150,000",$ -,"$ 150,000"
23,D,Marceline,DWLSL-246-23,LSLI,"2,012","$ 250,000",$ -,"$ 250,000"
24,D,Windsor,DWLSL-247-23,LSLI,"2,805","$ 190,000",$ -,"$ 190,000"
25,D,Andrew PWSD 2,DWLSL-248-23,LSLI,"3,548","$ 240,000",$ -,"$ 240,000"
26,,Kearney,DWLSL-249-23,LSLI,"10,404","$ 26,000","$ 15,340","$ 10,660"
27,D,Carterville,DWLSL-250-23,LSLI,"1,855","$ 260,605",$ -,"$ 260,605"
28,D,Fredericktown,DWLSL-251-23,LSLI,"4,274","$ 250,000",$ -,"$ 250,000"
29,,Trenton,DWLSL-252-23,"LSLI, LSLR","5,600","$ 88,000","$ 51,920","$ 36,080"
30,D,Hermann,DWLSL-253-23,LSLI,"2,185","$ 422,142",$ -,"$ 422,142"
31,D,Stoddard PWSD 4,DWLSL-254-23,LSLI,"1,700","$ 300,000",$ -,"$ 300,000"
32,D,Qulin,DWLSL-255-23,"LSLI, LSLRP",946,"$ 126,875",$ -,"$ 126,875"

In [36]:
mo_6 = mo_pdfs[5].df

# manually fix merged columns
mo_6.iloc[5,0] = "D"
mo_6.iloc[5,1] = "Wayne PWSD 3"

mo_6.iloc[15,0] = "D"
mo_6.iloc[15,1] = "Westboro"

mo_6.iloc[16,0] = "D"
mo_6.iloc[16,1] = "Wayne PWSD 2"

mo_6.iloc[17,0] = "D"
mo_6.iloc[17,1] = "Warsaw"

mo_6.iloc[30,0] = "D"
mo_6.iloc[30,1] = "Wyatt"

# set columns
mo_6.columns = ['Disadvantaged', 'Applicant', "Project #", 'Description/Needs Category', 'Service Area Population',
                'IUP Amount Requested', 'Loan Amount', 'Additional Subsidization Amount']

# remove line breaks
mo_6['IUP Amount Requested'] = mo_6['IUP Amount Requested'].str.replace("\n", "")
mo_6['Loan Amount'] = mo_6['Loan Amount'].str.replace("\n", "")
mo_6['Additional Subsidization Amount'] = mo_6['Additional Subsidization Amount'].str.replace("\n", "")

### Manually add in the 5 projects that are missed at the top of p18

mo_6.loc[len(mo_6.index)] = ['D', 'Lancaster', 'DWLSL-289-23', 'LSLI', '700', '$200,000', '$-', '$200,000']
mo_6.loc[len(mo_6.index)] = ['D', 'Camden PWSD 1', 'DWLSL-290-23', 'LSLI, LSLRP', '750', '$250,000', '$ -', '$250,000']
mo_6.loc[len(mo_6.index)] = ['D', 'Livingston PWSD 3', 'DWLSL-291-23', 'LSLI', '2,125', '$175,000', '$ -', '$175,000']
mo_6.loc[len(mo_6.index)] = ['D', 'Middletown', 'DWLSL-292-23', 'LSLI', '167', '$250,000', '$ -', '$250,000']
mo_6.loc[len(mo_6.index)] = ['D', 'Urbana', 'DWLSL-293-23', 'LSLI', '387', '$100,000', '$ -', '$100,000']

mo_6

,Disadvantaged,Applicant,Project #,Description/Needs Category,Service Area Population,IUP Amount Requested,Loan Amount,Additional Subsidization Amount
0,D,Elmo,DWLSL-256-23,LSLI,165,"100,000$",$ -,"$ 100,000"
1,D,Burlington Junction,DWLSL-257-23,LSLI,500,"$ 250,000",$ -,"$ 250,000"
2,D,Gideon,DWLSL-258-23,"LSLI, LSLRP",692,"$ 202,930",$ -,"$ 202,930"
3,D,Everton,DWLSL-259-23,LSLI,325,"125,000$",$ -,"125,000$"
4,D,Holland,DWLSL-260-23,LSLI,229,"$ 250,000",$ -,"$ 250,000"
5,D,Wayne PWSD 3,DWLSL-261-23,LSLI,400,"100,000$",$ -,"$ 100,000"
6,D,Silex,DWLSL-262-23,LSLI,90,"$ 44,500",$ -,"44,500$"
7,D,Martinsburg,DWLSL-263-23,LSLI,300,"$ 15,000",$ -,"$ 15,000"
8,D,Herculaneum,DWLSL-264-23,LSLI,"4,273","424,680$",$ -,"424,680$"
9,D,Marquand,DWLSL-265-23,"LSLI, LSLRP",260,"$ 125,000",$ -,"125,000$"
10,D,East Prairie,DWLSL-266-23,LSLI,"2,890","$ 200,000",$ -,"$ 200,000"
11,D,Greenfield,DWLSL-267-23,LSLI,"1,340","200,000$",$ -,"200,000$"
12,D,Flemington,DWLSL-268-23,LSLI,110,"$ 95,000",$ -,"$ 95,000"
13,D,Huntsville,DWLSL-269-23,"LSLI, LSLRP, LSLR","1,820","67,500$",$ -,"$ 67,500"
14,D,Pierce City,DWLSL-270-23,LSLI,"1,462","115,000$",$ -,"$ 115,000"
15,D,Westboro,DWLSL-271-23,LSLI,112,"$ 55,000",$ -,"$ 55,000"
16,D,Wayne PWSD 2,DWLSL-272-23,"LSLI, LSLRP",950,"168,365$",$ -,"168,365$"
17,D,Warsaw,DWLSL-273-23,LSLI,"2,334","$ 500,000",$ -,"500,000$"
18,D,Fillmore,DWLSL-274-23,LSLI,284,"$ 250,000",$ -,"250,000$"
19,D,Caruthersville,DWLSL-275-23,LSLI,"5,518","$ 900,000",$ -,"$ 900,000"
20,D,Hayti Heights,DWLSL-276-23,"LSLI, LSLRP",515,"$ 132,400",$ -,"$ 132,400"
21,D,Sheldon,DWLSL-277-23,"LSLI, LSLR",543,"$ 130,000",$ -,"$ 130,000"
22,D,Plattsburg,DWLSL-278-23,LSLI,"2,900","$ 140,000",$ -,"$ 140,000"
23,D,Clark,DWLSL-279-23,LSLI,253,"$ 200,000",$ -,"$ 200,000"
24,D,Farber,DWLSL-280-23,LSLI,275,"$ 5,000",$ -,"$ 5,000"
25,D,Iberia,DWLSL-281-23,LSLI,703,"$ 155,000",$ -,"$ 155,000"
26,D,Mound City,DWLSL-282-23,LSLI,"1,154","$ 200,000",$ -,"$ 200,000"
27,D,Craig,DWLSL-283-23,LSLI,220,"$ 55,000",$ -,"$ 55,000"
28,D,Grant City,DWLSL-284-23,LSLI,828,"$ 95,000",$ -,"$ 95,000"
29,D,Pilot Grove,DWLSL-285-23,LSLI,667,"$ 140,000",$ -,"$ 140,000"
30,D,Wyatt,DWLSL-286-23,LSLI,280,"$ 180,000",$ -,"$ 180,000"
31,D,Campbell,DWLSL-287-23,LSLI,"1,768","$ 833,000",$ -,"$ 833,000"
32,D,Forest City,DWLSL-288-23,LSLI,260,"$ 72,500",$ -,"$ 72,500"
33,D,Lancaster,DWLSL-289-23,LSLI,700,"$200,000",$-,"$200,000"
34,D,Camden PWSD 1,DWLSL-290-23,"LSLI, LSLRP",750,"$250,000",$-,"$250,000"
35,D,Livingston PWSD 3,DWLSL-291-23,LSLI,"2,125","$175,000",$-,"$175,000"
36,D,Middletown,DWLSL-292-23,LSLI,167,"$250,000",$-,"$250,000"
37,D,Urbana,DWLSL-293-23,LSLI,387,"$100,000",$-,"$100,000"
38,D,Lancaster,DWLSL-289-23,LSLI,700,"$200,000",$-,"$200,000"
39,D,Camden PWSD 1,DWLSL-290-23,"LSLI, LSLRP",750,"$250,000",$ -,"$250,000"
40,D,Livingston PWSD 3,DWLSL-291-23,LSLI,"2,125","$175,000",$ -,"$175,000"
41,D,Middletown,DWLSL-292-23,LSLI,167,"$250,000",$ -,"$250,000"
42,D,Urbana,DWLSL-293-23,LSLI,387,"$100,000",$ -,"$100,000"

In [43]:
mo_7 = mo_pdfs[6].df

# manually fix spliced rows
mo_7.iloc[20,0] = "Jefferson Co. Sewer District Sommer Set Lakes"

mo_7 = mo_7.iloc[2:21,].reset_index(drop=True).copy()

# set columns
mo_7.columns = ['Applicant', "Project #", 'Description/Needs Category', 'Service Area Population',
                'IUP Amount Requested', 'Loan Amount', 'Additional Subsidization Amount']

# remove line breaks
mo_7['IUP Amount Requested'] = mo_7['IUP Amount Requested'].str.replace("\n", "")
mo_7['Loan Amount'] = mo_7['Loan Amount'].str.replace("\n", "")
mo_7['Additional Subsidization Amount'] = mo_7['Additional Subsidization Amount'].str.replace("\n", "")

mo_7

,Applicant,Project #,Description/Needs Category,Service Area Population,IUP Amount Requested,Loan Amount,Additional Subsidization Amount
0,Troy,DWLSL-294-23,LSLI,"13,358","$ 1,010,830","$ 908,330","$ 102,500"
1,Ray PWSD 1,DWLSL-295-23,LSLI,"2,450","$ 29,400","$ 17,346","$ 12,054"
2,Conway,DWLSL-296-23,LSLI,788,"200,000$","$ 118,000","$ 82,000"
3,Platte County PWSD 1,DWLSL-297-23,"LSLI, LSLRP","7,000","$ 200,000","$ 118,000","$ 82,000"
4,Moberly,DWLSL-298-23,"LSLI, LSLRP","13,783","$ 235,000","$ 138,650","$ 96,350"
5,Malden,DWLSL-299-23,"LSLI, LSLRP","3,706","418,725$","$ 316,225","$ 102,500"
6,Archie,DWLSL-300-23,LSLI,"1,268","$ 378,000","$ 275,500","$ 102,500"
7,Taney County PWSD 2,DWLSL-301-23,LSLI,"5,500","$ 15,000","$ 8,850","$ 6,150"
8,St. Peters,DWLSL-302-23,LSLI,"57,732","$ 200,000","$ 118,000","$ 82,000"
9,Kirkwood,DWLSL-303-23,"LSLRP, LSLR","29,371","$ 100,000","$ 59,000","$ 41,000"
10,Jasper PWSD1,DWLSL-304-23,LSLI,"5,500","$ 1,507,000","$ 1,404,500","$ 102,500"
11,Boone PWSD 9,DWLSL-305-23,"LSLI, LSLRP","16,000","$ 85,000","$ 50,150","$ 34,850"
12,Springfield,DWLSL-306-23,LSLI,"167,601","$ 766,400","$ 663,900","$ 102,500"
13,Rolla,DWLSL-307-23,"LSLI, LSLRP","20,322","$ 300,000","$ 197,500","$ 102,500"
14,Greene County PWSD 6,DWLSL-308-23,LSLI,481,"$ 250,000","$ 147,500","$ 102,500"
15,Maries PWSD 1,DWLSL-309-23,LSLI,962,"$ 37,600","$ 22,184","$ 15,416"
16,Waynesville,DWLSL-310-23,LSLI,"5,260","$ 300,000","$ 197,500","$ 102,500"
17,Livingston PWSD 1,DWLSL-311-23,"LSLI, LSLRP, LSLR",531,"$ 360,000","$ 257,500","$ 102,500"
18,Jefferson Co. Sewer District Sommer Set Lakes,DWLSL-312-23,LSLI,"1,625","$ 65,000","$ 38,350","$ 26,650"

In [46]:
mo_8 = mo_pdfs[7].df

mo_8.iloc[12:,] = ['MO American Mexico', 'DWLSL-326-23', 'LSLR', '11,523', '$1,675,000', '$988,250', '$686,750']

mo_8 = mo_8.iloc[1:13,].reset_index(drop=True).copy()

mo_8.columns = ['Applicant', "Project #", 'Description/Needs Category', 'Service Area Population',
                'IUP Amount Requested', 'Loan Amount', 'Additional Subsidization Amount']

# remove line breaks
mo_8['IUP Amount Requested'] = mo_8['IUP Amount Requested'].str.replace("\n", "")
mo_8['Loan Amount'] = mo_8['Loan Amount'].str.replace("\n", "")
mo_8['Additional Subsidization Amount'] = mo_8['Additional Subsidization Amount'].str.replace("\n", "")

mo_8

,Applicant,Project #,Description/Needs Category,Service Area Population,IUP Amount Requested,Loan Amount,Additional Subsidization Amount
0,Pleasant Hill,DWLSL-315-23,LSLI,"8,517","$ 1,184,000","$ 1,081,500","102,500$"
1,Columbia,DWLSL-316-23,LSLI,"128,725","$ 249,546","$ 147,232","$ 102,314"
2,Union,DWLSL-317-23,LSLI,"12,348","125,000$","$ 73,750","51,250$"
3,Seneca,DWLSL-318-23,LSLI,"2,230","$ 145,000","$ 85,550","59,450$"
4,Perryville,DWLSL-319-23,LSLI,"8,488","$ 796,650","$ 694,150","$ 102,500"
5,Risco,DWLSL-320-23,"LSLI, LSLRP",257,"111,000$","$ 65,490","45,510$"
6,Chaffee,DWLSL-321-23,LSLI,"3,057","$ 200,000","$ 118,000","$ 82,000"
7,MO American St. Louis/St. Charles,DWLSL-322-23,LSLR,"997,187","$ 51,600,000","$ 49,550,000","$ 2,050,000"
8,MO American St. Joseph,DWLSL-323-23,LSLR,"71,602","11,600,000$","$ 9,550,000","2,050,000$"
9,MO American Joplin,DWLSL-324-23,LSLR,"51,946","$ 5,580,000","$ 3,530,000","$ 2,050,000"
10,MO American Jefferson City,DWLSL-325-23,LSLR,"42,772","$ 3,170,000","$ 1,870,300","$ 1,299,700"
11,MO American Mexico,DWLSL-326-23,LSLR,"11,523","$1,675,000","$988,250","$686,750"

### Combine Pages & Export

In [50]:
# tables mo_1 -> mo_6 are Lead Service Line Fundable

mo_lsl_fundable = pd.concat([mo_1, mo_2, mo_3, mo_4, mo_5, mo_6], ignore_index=True).reset_index(drop=True)
mo_lsl_fundable.to_csv("../data/year1/csv/25-Missouri_LSLFundable.csv", index=False)

# tables mo_7 + mo_8 are FUNDABLE CONTINGENCY LIST
mo_lsl_contingency = pd.concat([mo_7, mo_8], ignore_index=True).reset_index(drop=True)
mo_lsl_contingency.to_csv("../data/year1/csv/25-Missouri_LSLContingency.csv", index=False)